<?php

declare(strict_types=1);

final class CustomerService {
    public static function accountLabel(array $a): string {return self::bestLabel((string)($a['display_name']??''),(string)($a['original_name']??''),(string)($a['source_username']??''));}
    public static function list(string $q='', bool $includeInactive=false, int $companyId=0, int $panelId=0): array {
        $pdo=Database::connection();
        $sql="SELECT c.id,c.display_name,c.notes,c.active,c.updated_at,COUNT(DISTINCT ca.account_id) account_count,
        GROUP_CONCAT(DISTINCT a.source_username ORDER BY a.source_username SEPARATOR '، ') usernames,
        GROUP_CONCAT(DISTINCT pn.name ORDER BY pn.name SEPARATOR '، ') panel_names,
        GROUP_CONCAT(DISTINCT co.name ORDER BY co.name SEPARATOR '، ') company_names,
        COALESCE(SUM(CASE WHEN r.status='final' THEN rr.received ELSE 0 END),0) received,
        COALESCE(SUM(CASE WHEN r.status='final' THEN rr.paid ELSE 0 END),0) paid,
        COALESCE(SUM(CASE WHEN r.status='final' THEN rr.commission ELSE 0 END),0) commission
        FROM customers c JOIN customer_accounts ca ON ca.customer_id=c.id JOIN accounts a ON a.id=ca.account_id JOIN panels pn ON pn.id=a.panel_id JOIN companies co ON co.id=pn.company_id LEFT JOIN daily_report_rows rr ON rr.account_id=ca.account_id LEFT JOIN daily_reports r ON r.id=rr.daily_report_id
        WHERE 1=1";$params=[];
        if(!$includeInactive)$sql.=' AND c.active=1';
        if($q!==''){$sql.=" AND (c.display_name LIKE ? OR a.source_username LIKE ? OR a.original_name LIKE ? OR a.display_name LIKE ?)";$like='%'.$q.'%';array_push($params,$like,$like,$like,$like);}
        if($companyId>0){$sql.=' AND pn.company_id=?';$params[]=$companyId;}
        if($panelId>0){$sql.=' AND a.panel_id=?';$params[]=$panelId;}
        $sql.=' GROUP BY c.id ORDER BY c.active DESC,c.display_name,c.id';$st=$pdo->prepare($sql);$st->execute($params);$rows=$st->fetchAll();
        foreach($rows as &$r){if(!self::usableName((string)$r['display_name'])){$first=self::firstAccountForCustomer((int)$r['id']);if($first)$r['display_name']=self::accountLabel($first);}}
        return $rows;
    }
    public static function filterOptions(): array {$pdo=Database::connection();return ['companies'=>$pdo->query("SELECT id,name FROM companies WHERE active=1 ORDER BY name")->fetchAll(),'panels'=>$pdo->query("SELECT p.id,p.name,p.company_id,c.name company_name FROM panels p JOIN companies c ON c.id=p.company_id WHERE p.active=1 AND c.active=1 ORDER BY c.name,p.name")->fetchAll()];}
    public static function updateAccountProfile(int $customerId,int $accountId,string $originalName,string $displayName,string $rateType,bool $active,int $uid): void {if(!in_array($rateType,['general','special'],true))throw new RuntimeException('نوع نرخ معتبر نیست.');$pdo=Database::connection();$st=$pdo->prepare('SELECT COUNT(*) FROM customer_accounts WHERE customer_id=? AND account_id=?');$st->execute([$customerId,$accountId]);if(!(int)$st->fetchColumn())throw new RuntimeException('این حساب متعلق به این مشتری نیست.');$pdo->prepare('UPDATE accounts SET original_name=?,display_name=?,rate_type=?,active=? WHERE id=?')->execute([trim($originalName),trim($displayName),$rateType,$active?1:0,$accountId]);self::refreshCustomerName($customerId);Logger::audit('customer.account_profile_updated',['customer_id'=>$customerId,'account_id'=>$accountId,'user_id'=>$uid,'rate_type'=>$rateType,'active'=>$active]);}
    public static function suggestionsForCustomer(int $customerId): array {$c=self::get($customerId);if(!$c||empty($c['accounts']))return [];$keys=[];foreach($c['accounts'] as $a){$k=self::accountKey($a);if($k!=='')$keys[$k]=true;}$pdo=Database::connection();$st=$pdo->prepare("SELECT a.id,a.source_username,a.original_name,a.display_name,a.rate_type,a.active,p.name panel_name,p.company_id,c.name company_name,ca.customer_id FROM accounts a JOIN panels p ON p.id=a.panel_id JOIN companies c ON c.id=p.company_id LEFT JOIN customer_accounts ca ON ca.account_id=a.id WHERE (ca.customer_id IS NULL OR ca.customer_id<>?) ORDER BY c.name,p.name,a.source_username");$st->execute([$customerId]);$out=[];foreach($st->fetchAll() as $r){$k=self::accountKey($r);if($k!==''&&isset($keys[$k])){$r['ui_name']=self::accountLabel($r);$out[]=$r;}}return $out;}
    public static function get(int $id): ?array {$st=Database::connection()->prepare('SELECT * FROM customers WHERE id=?');$st->execute([$id]);$c=$st->fetch();if(!$c)return null;$c['accounts']=self::accounts($id);if(!self::usableName((string)$c['display_name'])&&!empty($c['accounts']))$c['display_name']=self::accountLabel($c['accounts'][0]);$c['ledger']=self::ledger($id);return $c;}
    public static function accounts(int $customerId): array {$st=Database::connection()->prepare("SELECT a.id,a.source_username,a.original_name,a.display_name,a.rate_type,a.active,p.id panel_id,p.name panel_name,c.id company_id,c.name company_name FROM customer_accounts ca JOIN accounts a ON a.id=ca.account_id JOIN panels p ON p.id=a.panel_id JOIN companies c ON c.id=p.company_id WHERE ca.customer_id=? ORDER BY c.name,p.name,a.source_username");$st->execute([$customerId]);$rows=$st->fetchAll();foreach($rows as &$r)$r['ui_name']=self::accountLabel($r);return $rows;}
    public static function unlinkedAccounts(string $q='',int $excludeCustomerId=0): array {$sql="SELECT a.id,a.source_username,a.original_name,a.display_name,p.name panel_name,c.name company_name,ca.customer_id FROM accounts a JOIN panels p ON p.id=a.panel_id JOIN companies c ON c.id=p.company_id LEFT JOIN customer_accounts ca ON ca.account_id=a.id WHERE 1=1";$params=[];if($excludeCustomerId>0){$sql.=' AND (ca.customer_id IS NULL OR ca.customer_id<>?)';$params[]=$excludeCustomerId;}else{$sql.=' AND ca.account_id IS NULL';}if($q!==''){$sql.=' AND (a.source_username LIKE ? OR a.original_name LIKE ? OR a.display_name LIKE ? OR p.name LIKE ? OR c.name LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like,$like);}$sql.=' ORDER BY COALESCE(NULLIF(a.display_name,\'\'),NULLIF(a.original_name,\'\'),a.source_username),a.source_username LIMIT 1000';$st=Database::connection()->prepare($sql);$st->execute($params);$rows=$st->fetchAll();foreach($rows as &$r)$r['ui_name']=self::accountLabel($r);return $rows;}
    public static function autoGroupUnlinked(?int $uid=null): array {$pdo=Database::connection();self::ensureExclusionTable($pdo);$linked=$pdo->query("SELECT cu.id customer_id,a.id account_id,a.display_name,a.original_name,a.source_username,CASE WHEN ex.account_id IS NULL THEN 0 ELSE 1 END excluded FROM customers cu JOIN customer_accounts ca ON ca.customer_id=cu.id JOIN accounts a ON a.id=ca.account_id LEFT JOIN customer_autogroup_exclusions ex ON ex.account_id=a.id WHERE cu.active=1 ORDER BY cu.id")->fetchAll();$map=[];foreach($linked as $r){$key=((int)$r['excluded']===1)?'ACCOUNT:'.(int)$r['account_id']:self::accountKey($r);if($key!==''&&!isset($map[$key]))$map[$key]=(int)$r['customer_id'];}
        $rows=$pdo->query("SELECT a.id,a.source_username,a.original_name,a.display_name,CASE WHEN ex.account_id IS NULL THEN 0 ELSE 1 END excluded FROM accounts a LEFT JOIN customer_accounts ca ON ca.account_id=a.id LEFT JOIN customer_autogroup_exclusions ex ON ex.account_id=a.id WHERE ca.account_id IS NULL ORDER BY a.id")->fetchAll();$groups=[];foreach($rows as $r){$key=((int)$r['excluded']===1)?'ACCOUNT:'.(int)$r['id']:self::accountKey($r);if($key==='')$key='USERNAME:'.self::upper((string)$r['source_username']);$groups[$key][]=$r;}
        $created=0;$linkedCount=0;$pdo->beginTransaction();try{$insCustomer=$pdo->prepare('INSERT INTO customers(display_name,created_by) VALUES(?,?)');$insLink=$pdo->prepare('INSERT IGNORE INTO customer_accounts(customer_id,account_id,linked_by) VALUES(?,?,?)');foreach($groups as $key=>$group){$customerId=$map[$key]??0;if(!$customerId){$label=self::accountLabel($group[0]);$insCustomer->execute([$label,$uid]);$customerId=(int)$pdo->lastInsertId();$map[$key]=$customerId;$created++;}foreach($group as $r){$insLink->execute([$customerId,(int)$r['id'],$uid]);if($insLink->rowCount())$linkedCount++;}self::refreshCustomerName($customerId,$pdo);}self::cleanupEmptyCustomers($pdo);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}if($created||$linkedCount)Logger::audit('customer.autogroup',['created'=>$created,'linked'=>$linkedCount,'user_id'=>$uid]);return ['created'=>$created,'linked'=>$linkedCount];}
    public static function create(string $name,array $accountIds,int $uid): int {$name=trim($name);$ids=array_values(array_unique(array_filter(array_map('intval',$accountIds))));if(!$ids)throw new RuntimeException('حداقل یک حساب را انتخاب کن.');if($name==='')$name='مشتری';$pdo=Database::connection();$pdo->beginTransaction();try{$st=$pdo->prepare('INSERT INTO customers(display_name,created_by) VALUES(?,?)');$st->execute([$name,$uid]);$id=(int)$pdo->lastInsertId();self::linkInternal($id,$ids,$uid,$pdo);self::refreshCustomerName($id,$pdo);$pdo->commit();Logger::audit('customer.created',['customer_id'=>$id,'name'=>$name,'accounts'=>$ids]);return $id;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    public static function update(int $id,string $name,string $notes,int $uid,?bool $active=null,?string $rateType=null): void {$name=trim($name);if($name===''){$a=self::firstAccountForCustomer($id);$name=$a?self::accountLabel($a):'مشتری';}$pdo=Database::connection();$pdo->beginTransaction();try{if($active===null)$pdo->prepare('UPDATE customers SET display_name=?,notes=? WHERE id=?')->execute([$name,trim($notes),$id]);else $pdo->prepare('UPDATE customers SET display_name=?,notes=?,active=? WHERE id=?')->execute([$name,trim($notes),$active?1:0,$id]);if($rateType!==null){if(!in_array($rateType,['general','special'],true))throw new RuntimeException('نوع نرخ معتبر نیست.');$pdo->prepare('UPDATE accounts a JOIN customer_accounts ca ON ca.account_id=a.id SET a.rate_type=? WHERE ca.customer_id=?')->execute([$rateType,$id]);}$pdo->commit();Logger::audit('customer.updated',['customer_id'=>$id,'user_id'=>$uid,'active'=>$active,'rate_type'=>$rateType]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    public static function link(int $id,array $accountIds,int $uid): void {$ids=array_values(array_unique(array_filter(array_map('intval',$accountIds))));if(!$ids)return;$pdo=Database::connection();self::ensureExclusionTable($pdo);$pdo->beginTransaction();try{self::linkInternal($id,$ids,$uid,$pdo);$marks=implode(',',array_fill(0,count($ids),'?'));$pdo->prepare("DELETE FROM customer_autogroup_exclusions WHERE account_id IN ($marks)")->execute($ids);self::refreshCustomerName($id,$pdo);self::cleanupEmptyCustomers($pdo);$pdo->commit();Logger::audit('customer.accounts_linked',['customer_id'=>$id,'accounts'=>$ids]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    private static function linkInternal(int $id,array $ids,?int $uid,?PDO $pdo=null): void {$pdo=$pdo?:Database::connection();$del=$pdo->prepare('DELETE FROM customer_accounts WHERE account_id=? AND customer_id<>?');$ins=$pdo->prepare('INSERT INTO customer_accounts(customer_id,account_id,linked_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE linked_by=VALUES(linked_by)');foreach($ids as $aid){$del->execute([$aid,$id]);$ins->execute([$id,$aid,$uid]);}}
    public static function unlink(int $id,int $accountId,int $uid): void {$pdo=Database::connection();self::ensureExclusionTable($pdo);$pdo->beginTransaction();try{$a=$pdo->prepare('SELECT id,source_username,original_name,display_name FROM accounts WHERE id=?');$a->execute([$accountId]);$account=$a->fetch();if(!$account)throw new RuntimeException('حساب پیدا نشد.');$pdo->prepare('DELETE FROM customer_accounts WHERE customer_id=? AND account_id=?')->execute([$id,$accountId]);$pdo->prepare('INSERT INTO customer_autogroup_exclusions(account_id,excluded_by) VALUES(?,?) ON DUPLICATE KEY UPDATE excluded_by=VALUES(excluded_by),excluded_at=CURRENT_TIMESTAMP')->execute([$accountId,$uid]);$pdo->prepare('INSERT INTO customers(display_name,created_by) VALUES(?,?)')->execute([self::accountLabel($account),$uid]);$newId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO customer_accounts(customer_id,account_id,linked_by) VALUES(?,?,?)')->execute([$newId,$accountId,$uid]);self::refreshCustomerName($id,$pdo);self::cleanupEmptyCustomers($pdo);$pdo->commit();Logger::audit('customer.account_unlinked',['customer_id'=>$id,'new_customer_id'=>$newId,'account_id'=>$accountId,'user_id'=>$uid]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    public static function delete(int $id,int $uid): void {$pdo=Database::connection();self::ensureExclusionTable($pdo);$pdo->beginTransaction();try{$ids=$pdo->prepare('SELECT account_id FROM customer_accounts WHERE customer_id=?');$ids->execute([$id]);$accountIds=array_map('intval',array_column($ids->fetchAll(),'account_id'));$pdo->prepare('DELETE FROM customer_accounts WHERE customer_id=?')->execute([$id]);$pdo->prepare('UPDATE customers SET active=0 WHERE id=?')->execute([$id]);foreach($accountIds as $aid){$a=$pdo->prepare('SELECT id,source_username,original_name,display_name FROM accounts WHERE id=?');$a->execute([$aid]);$acc=$a->fetch();if(!$acc)continue;$pdo->prepare('INSERT INTO customers(display_name,created_by) VALUES(?,?)')->execute([self::accountLabel($acc),$uid]);$newId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO customer_accounts(customer_id,account_id,linked_by) VALUES(?,?,?)')->execute([$newId,$aid,$uid]);$pdo->prepare('INSERT INTO customer_autogroup_exclusions(account_id,excluded_by) VALUES(?,?) ON DUPLICATE KEY UPDATE excluded_by=VALUES(excluded_by),excluded_at=CURRENT_TIMESTAMP')->execute([$aid,$uid]);}$pdo->commit();Logger::audit('customer.deleted',['customer_id'=>$id,'user_id'=>$uid]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    public static function ledger(int $id,?string $from=null,?string $to=null): array {$sql="SELECT r.id report_id,r.report_date,c.name company_name,p.name panel_name,rr.source_username,COALESCE(NULLIF(rr.display_name_snapshot,''),NULLIF(rr.original_name_snapshot,''),rr.source_username) name,rr.member_win,rr.rate_value_snapshot,rr.loss_percent_snapshot,rr.commission,rr.received,rr.paid FROM customer_accounts ca JOIN daily_report_rows rr ON rr.account_id=ca.account_id JOIN daily_reports r ON r.id=rr.daily_report_id AND r.status='final' LEFT JOIN panels p ON p.id=rr.panel_id LEFT JOIN companies c ON c.id=r.company_id WHERE ca.customer_id=?";$params=[$id];if($from){$sql.=' AND r.report_date>=?';$params[]=AccountingService::normalizeBusinessDate($from);}if($to){$sql.=' AND r.report_date<=?';$params[]=AccountingService::normalizeBusinessDate($to);}$sql.=' ORDER BY r.report_date DESC,r.id DESC,rr.id';$st=Database::connection()->prepare($sql);$st->execute($params);$rows=$st->fetchAll();$tot=['received'=>0.0,'paid'=>0.0,'commission'=>0.0];foreach($rows as &$r){foreach(['member_win','commission','received','paid'] as $k)$r[$k]=(float)$r[$k];$tot['received']+=$r['received'];$tot['paid']+=$r['paid'];$tot['commission']+=$r['commission'];}unset($r);$tot['net']=$tot['received']-$tot['paid'];return ['rows'=>$rows,'totals'=>$tot];}
    private static function usableName(string $s): bool {$n=preg_replace('/\s+/u',' ',trim($s))??trim($s);if($n==='')return false;$compact=preg_replace('/[\s\-–—_\.]+/u','',$n)??$n;return $compact!=='' && !in_array($compact,['نامشخص','بدوننام'],true);}
    private static function bestLabel(string $display,string $original,string $username): string {if(self::usableName($display))return trim($display);if(self::usableName($original))return trim($original);return trim($username)!==''?trim($username):'بدون نام';}
    private static function accountKey(array $a): string {$label=self::bestLabel((string)($a['display_name']??''),(string)($a['original_name']??''),(string)($a['source_username']??''));if($label===(string)($a['source_username']??''))return 'USERNAME:'.self::upper($label);$base=self::baseDisplayName($label);$base=strtr($base,['ي'=>'ی','ى'=>'ی','ك'=>'ک','أ'=>'ا','إ'=>'ا','آ'=>'ا']);$base=preg_replace('/[^\pL\pN]+/u','',$base)??$base;return $base!==''?'NAME:'.self::upper($base):'USERNAME:'.self::upper((string)($a['source_username']??''));}
    private static function baseDisplayName(string $name): string {$name=preg_replace('/\s+/u',' ',trim($name))??trim($name);$base=preg_replace('/\s*[0-9۰-۹٠-٩]+\s*$/u','',$name)??$name;return trim($base)!==''?trim($base):$name;}
    private static function upper(string $s): string {return function_exists('mb_strtoupper')?mb_strtoupper($s,'UTF-8'):strtoupper($s);}
    private static function firstAccountForCustomer(int $customerId): ?array {$st=Database::connection()->prepare('SELECT a.id,a.source_username,a.original_name,a.display_name FROM customer_accounts ca JOIN accounts a ON a.id=ca.account_id WHERE ca.customer_id=? ORDER BY a.id LIMIT 1');$st->execute([$customerId]);$a=$st->fetch();return $a?:null;}
    private static function refreshCustomerName(int $customerId,?PDO $pdo=null): void {$pdo=$pdo?:Database::connection();$st=$pdo->prepare('SELECT c.display_name,a.source_username,a.original_name,a.display_name account_display FROM customers c LEFT JOIN customer_accounts ca ON ca.customer_id=c.id LEFT JOIN accounts a ON a.id=ca.account_id WHERE c.id=? ORDER BY a.id LIMIT 1');$st->execute([$customerId]);$r=$st->fetch();if(!$r||!$r['source_username'])return;if(!self::usableName((string)$r['display_name']))$pdo->prepare('UPDATE customers SET display_name=? WHERE id=?')->execute([self::bestLabel((string)$r['account_display'],(string)$r['original_name'],(string)$r['source_username']),$customerId]);}
    private static function cleanupEmptyCustomers(PDO $pdo): void {$pdo->exec("UPDATE customers c LEFT JOIN customer_accounts ca ON ca.customer_id=c.id SET c.active=0 WHERE ca.customer_id IS NULL AND c.active=1");}
    private static function ensureExclusionTable(PDO $pdo): void {if(self::tableExists($pdo,'customer_autogroup_exclusions'))return;$pdo->exec("CREATE TABLE customer_autogroup_exclusions (account_id BIGINT UNSIGNED PRIMARY KEY,excluded_by BIGINT UNSIGNED NULL,excluded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_customer_autogroup_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,CONSTRAINT fk_customer_autogroup_user FOREIGN KEY (excluded_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");}
    private static function tableExists(PDO $pdo,string $table): bool {$st=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$st->execute([$table]);return (bool)$st->fetchColumn();}
}
