<?php

declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';
Auth::requireLogin();
$settings=SettingsService::all();header('Cache-Control: no-store, no-cache, must-revalidate');
$report=AccountingService::reportWithRows((int)($_GET['id']??0));
if(!$report){http_response_code(404);exit('گزارش پیدا نشد.');}
$recv=[];$pay=[];
foreach($report['rows'] as $r){
    $name=trim((string)($r['display_name_snapshot']?:($r['original_name_snapshot']?:$r['source_username'])));
    if((float)$r['received']>0)$recv[]=['name'=>$name,'amount'=>(float)$r['received']];
    if((float)$r['paid']>0)$pay[]=['name'=>$name,'amount'=>(float)$r['paid']];
}
$recvColor=SettingsService::themeFill($settings['theme_recv'],$settings);
$payColor=SettingsService::themeFill($settings['theme_pay'],$settings);
$winColor=SettingsService::themeFill($settings['theme_site_win']??$settings['theme_pay'],$settings);
$lossColor=SettingsService::themeFill($settings['theme_site_loss']??$settings['theme_recv'],$settings);
$net=(float)$report['total_received']-(float)$report['total_paid'];
$title='حسابرسی اکانت‌های '.$report['company_name'];
$date=AccountingService::displayBusinessDate((string)$report['report_date']);
$unit=SettingsService::moneyUnit($settings);
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=e($title)?></title><style>
@import url("https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;700;900&display=swap");<?=SettingsService::cssVars($settings)?>
*{box-sizing:border-box}body{margin:0;background:#eef1f5;color:#111;font-family:var(--font-print,Vazirmatn,Tahoma,sans-serif);padding:12px}.toolbar{display:flex;gap:8px;justify-content:center;margin-bottom:10px}.toolbar button,.toolbar a{border:0;border-radius:10px;padding:10px 14px;background:#fff;color:#111;font:700 14px var(--font-form);text-decoration:none;cursor:pointer}.sheet{width:min(100%,900px);margin:auto;background:#fff;padding:22px;border:1px solid #222}.title{text-align:center;font-size:30px;font-weight:900;margin:0}.date{text-align:center;font-size:24px;font-weight:800;margin:8px 0 18px}.unit{text-align:center;font-size:12px;color:#555;margin-bottom:10px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:54px;direction:ltr}.panel{direction:rtl;border:1px solid #222}.panel h2{margin:0;padding:11px;text-align:center;font-size:22px;border-bottom:1px solid #222}.panel.recv h2,.panel.recv th,.panel.recv td{background:<?=$recvColor?>}.panel.pay h2,.panel.pay th,.panel.pay td{background:<?=$payColor?>}.panel table{width:100%;border-collapse:collapse;table-layout:fixed}.panel th,.panel td{border:1px solid #222;padding:8px 9px;text-align:center;font-size:16px}.panel th{background:#fff}.panel td.amount{font-size:22px;font-weight:900;direction:ltr}.panel td.name{font-weight:700}.totals{width:48%;margin-top:48px;border-collapse:collapse}.totals th,.totals td{border:1px solid #222;padding:9px 12px;font-size:20px}.totals th{text-align:right}.totals td{font-weight:900;direction:ltr;text-align:center}.totals .recv>*{background:<?=$recvColor?>}.totals .pay>*{background:<?=$payColor?>}.totals .result>*{background:<?=$net>0?$winColor:($net<0?$lossColor:'#f3f4f6')?>}.empty{padding:18px;text-align:center;color:#666;background:#fff!important}
@media(max-width:700px){body{padding:4px}.sheet{padding:8px}.title{font-size:21px}.date{font-size:18px}.cols{gap:8px}.panel h2{font-size:15px;padding:7px}.panel th,.panel td{font-size:10px;padding:5px 3px}.panel td.amount{font-size:14px}.totals{width:100%;margin-top:16px}.totals th,.totals td{font-size:14px;padding:7px}.toolbar{position:sticky;top:0;z-index:3;background:#eef1f5;padding:4px;margin:0 0 6px}.toolbar>*{flex:1;text-align:center}}
@media print{@page{size:A4 portrait;margin:8mm}body{background:#fff;padding:0}.toolbar{display:none}.sheet{width:100%;border:0;padding:0}.panel h2,.panel td,.totals *{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body><div class="toolbar"><button onclick="downloadSummaryImage()">ذخیره تصویر</button><button onclick="window.print()">چاپ / PDF</button><a href="index.php?page=entry&report=<?=e($report['id'])?>">بازگشت</a></div><main class="sheet" id="summarySheet"><h1 class="title"><?=e($title)?></h1><div class="date"><?=e($date)?></div><div class="unit">مبالغ به <?=e($unit)?></div><div class="cols"><section class="panel pay"><h2>پرداختی</h2><table><thead><tr><th>نام مشتری</th><th>مبلغ</th></tr></thead><tbody><?php if(!$pay):?><tr><td class="empty" colspan="2">موردی نیست</td></tr><?php endif;?><?php foreach($pay as $x):?><tr><td class="name"><?=e($x['name'])?></td><td class="amount"><?=e(SettingsService::money($x['amount'],$settings))?></td></tr><?php endforeach;?></tbody></table></section><section class="panel recv"><h2>دریافتی</h2><table><thead><tr><th>نام مشتری</th><th>مبلغ</th></tr></thead><tbody><?php if(!$recv):?><tr><td class="empty" colspan="2">موردی نیست</td></tr><?php endif;?><?php foreach($recv as $x):?><tr><td class="name"><?=e($x['name'])?></td><td class="amount"><?=e(SettingsService::money($x['amount'],$settings))?></td></tr><?php endforeach;?></tbody></table></section></div><table class="totals"><tr class="recv"><th>جمع دریافتی</th><td><?=e(SettingsService::money($report['total_received'],$settings))?></td></tr><tr class="pay"><th>جمع پرداختی</th><td><?=e(SettingsService::money($report['total_paid'],$settings))?></td></tr><tr class="result"><th><?=e($net>0?'برد':($net<0?'باخت':'تسویه'))?></th><td><?=e(SettingsService::money(abs($net),$settings))?></td></tr></table></main><canvas id="summaryCanvas" hidden></canvas><script>
const DATA=<?=json_encode(['title'=>$title,'date'=>$date,'unit'=>$unit,'recv'=>$recv,'pay'=>$pay,'total_received'=>(float)$report['total_received'],'total_paid'=>(float)$report['total_paid'],'net'=>$net,'colors'=>['recv'=>$recvColor,'pay'=>$payColor,'result'=>$net>0?$winColor:($net<0?$lossColor:'#f3f4f6')],'factor'=>SettingsService::scaleFactor($settings),'locale'=>$settings['digit_mode']==='fa'?'fa-IR':'en-US'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;
function fmt(n){return (Number(n||0)/DATA.factor).toLocaleString(DATA.locale,{maximumFractionDigits:2})}
async function downloadSummaryImage(){if(document.fonts)await document.fonts.ready;const rows=Math.max(DATA.recv.length,DATA.pay.length,1),w=1200,top=170,rowH=58,tableTop=top,totalTop=tableTop+92+rows*rowH+44,h=totalTop+190,c=document.getElementById('summaryCanvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);x.direction='rtl';x.textAlign='center';x.textBaseline='middle';const text=(t,cx,cy,max,font=24)=>{x.fillStyle='#111';x.font=`900 ${font}px Vazirmatn,Tahoma,Arial,sans-serif`;x.fillText(String(t),cx,cy,max)};text(DATA.title,w/2,46,w-40,42);text(DATA.date,w/2,100,w-40,30);text('مبالغ به '+DATA.unit,w/2,140,w-40,19);const gap=60,pad=28,colW=(w-gap-pad*2)/2;function box(left,y,width,height,color,label,font=23){x.fillStyle=color;x.fillRect(left,y,width,height);x.strokeStyle='#222';x.lineWidth=1.5;x.strokeRect(left,y,width,height);text(label,left+width/2,y+height/2,width-12,font)}function drawPanel(left,color,title,items){box(left,tableTop,colW,48,color,title,28);box(left,tableTop+48,colW/2,44,color,'مبلغ',20);box(left+colW/2,tableTop+48,colW/2,44,color,'نام مشتری',20);for(let i=0;i<rows;i++){const it=items[i];box(left,tableTop+92+i*rowH,colW/2,rowH,it?color:'#fff',it?fmt(it.amount):'',25);box(left+colW/2,tableTop+92+i*rowH,colW/2,rowH,it?color:'#fff',it?it.name:'',21)}}drawPanel(pad,DATA.colors.pay,'پرداختی',DATA.pay);drawPanel(pad+colW+gap,DATA.colors.recv,'دریافتی',DATA.recv);const tw=560;box(pad,totalTop,tw/2,54,DATA.colors.recv,fmt(DATA.total_received),26);box(pad+tw/2,totalTop,tw/2,54,DATA.colors.recv,'جمع دریافتی',24);box(pad,totalTop+54,tw/2,54,DATA.colors.pay,fmt(DATA.total_paid),26);box(pad+tw/2,totalTop+54,tw/2,54,DATA.colors.pay,'جمع پرداختی',24);box(pad,totalTop+108,tw/2,62,DATA.colors.result,fmt(Math.abs(DATA.net)),28);box(pad+tw/2,totalTop+108,tw/2,62,DATA.colors.result,DATA.net>0?'برد':DATA.net<0?'باخت':'تسویه',28);const blob=await new Promise(res=>c.toBlob(res,'image/png'));const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='report-summary.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),60000)}
</script></body></html>
